server.port=8080

page.size=5

jwt.secret=RAYS
jwt.expiration=3600000

#Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/project-10
spring.datasource.url=jdbc:mysql://mysql:3306/project-10

spring.datasource.username=root
spring.datasource.password=root

#Hibernate/JPA  Properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB53Dialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.datasource.hikari.connection-timeout=5000

#Email Server Parameters
smtp.server=smtp.gmail.com
smtp.port=465
email.login=sanjanagangrade62@gmail.com
email.pwd=szrw jekv gvit efcl